{
    "id": "/sourcegraph/codeintel-python",
    "cmd": null,
    "cpus": 1,
    "mem": 512,
    "disk": 0,
    "gpus": 0,
    "instances": 1,
    "executor": "",
    "requirePorts": false,
    "acceptedResourceRoles": ['*'],
    "container": {
        "type": "DOCKER",
        "docker": {
            "image": "sourcegraph/codeintel-python:18892_2018-07-27_ddc9943",
            "privileged": false,
            "forcePullImage": false
        },
        "portMappings": [
            {
                "containerPort": 2087,
                "hostPort": 0,
                "servicePort": 10013,
                "protocol": "tcp",
                "name": "main",
                "labels": {}
            }
        ]
    },
    "networks": [
        {
            "mode": "container/bridge"
        }
    ],
    "healthChecks": [
        {
            "protocol": "MESOS_TCP",
            "portIndex": 0,
            "delaySeconds": 15,
            "gracePeriodSeconds": 300,
            "intervalSeconds": 60,
            "timeoutSeconds": 20,
            "maxConsecutiveFailures": 3,
            "ipProtocol": "IPv4",
        }
    ],
    "labels": {
        "HAPROXY_GROUP": "lb"
    },
    "maxLaunchDelaySeconds": 3600,
    "backoffFactor": 1.15,
    "backoffSeconds": 1,
    "upgradeStrategy": {
        "minimumHealthCapacity": 1,
        "maximumOverCapacity": 1,
    },
    "killSelection": 'YOUNGEST_FIRST',
    "unreachableStrategy": {
        "inactiveAfterSeconds": 300,
        "expungeAfterSeconds": 600,
    },
}
